resolver: lts-12.9
packages:
- .
extra-deps:
- 'digestive-functors-0.8.4.0'
- 'digestive-functors-blaze-0.6.2.0'
- 'urlencoded-0.4.2.0'
- 'eventful-dynamodb-0.2.0'
- 'eventful-core-0.2.0'
- 'qrcode-0.1.2'
- 'JuicyPixels-3.3.1'
